name: test

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*.*'
  pull_request:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3.9.0
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'sbt'
          gpg-private-key: ${{ secrets.PGP_PRIVATE_KEY }}

      - name: Run tests
        run: sbt "+ test"
